#ifndef TL_CONFIG_H
#define TL_CONFIG_H
#include "TL_Device_ID.h"
#define PLATFORM 5
#define BOARD 1011
#define FUNCTION MODULE

#define LED MBED_LED
#define TIME MBED_TIME
#define BLUETOOTH MBED_BLUETOOTH
#define ACCELERATION MBED_MPU6050 
#define BUTTON MBED_BUTTON
#define BLE_LED MBED_BLE_LED

#endif
