#ifndef TL_CONFIG_H
#define TL_CONFIG_H

#include "TL_Device_ID.h"

#define PLATFORM 1
#define BOARD 1002

#define BUZZER GROVE_BUZZER 
#define RELAY GROVE_MINI_FAN
#define ATOMIZATION GROVE_WATER
#define RECORDER GROVE_RECORDER
#define BUTTON GROVE_BUTTON
#define SPEAKER GROVE_SPEAKER
#define SERVO GROVE_SERVO
#define DMX512 GROVE_DMX512
#define DISPLAY GROVE_LCD_RGB

#define BUZZER_DIGITAL_OUTPUT 3
#define RELAY_DIGITAL_OUTPUT 4  
#define ATOMIZATION_DIGITAL_OUTPUT 5 
#define RECORDER_DIGITAL_OUTPUT 7
#define RECORDER_DIGITAL_OUTPUT1 6
#define SPEAKER_DIGITAL_OUTPUT 8
#define SERVO_DIGITAL_OUTPUT 3
#define DMX512_DIGITAL_OUTPUT 4

#define BUTTON_DIGITAL_INPUT 2 

#endif