#ifndef TL_CONFIG_H
#define TL_CONFIG_H

#include "TL_Device_ID.h"

#define PLATFORM 1
#define BOARD 1002

#define HUMIDITY DHT11 
#define TEMPERATURE DHT11 
#define LIGHT GROVE_LIGHT
#define RELAY GROVE_RELAY
#define LED ARDUINO_LED
#define BUZZER GROVE_BUZZER 
#define SERIAL_TO_PARALLEL _74HC595 


#define RELAY_DIGITAL_OUTPUT 3   
#define TEMPERATURE_DIGITAL_OUTPUT 6 
#define HUMIDITY_DIGITAL_OUTPUT 7 
#define BUZZER_DIGITAL_OUTPUT 8 

#define _74HC595_DATA_DIGITAL_OUTPUT 2 
#define _74HC595_LATCH_DIGITAL_OUTPUT 4 
#define _74HC595_CLOCK_DIGITAL_OUTPUT 5 

#define LIGHT_ANALOG A0
#endif