#ifndef TL_CONFIG_H

#define TL_CONFIG_H
#include "TL_Device_ID.h"
#define PLATFORM 4
#define BOARD 1003

#define LED_DIGITAL_OUTPUT D17
#define SOIL_HUMIDITY_ANALOG PA0
#define LIGHT_ANALOG PA0
#define HUMIDITY_DIGITAL_INPUT PD4
#define TEMPERATURE_DIGITAL_INPUT PD4

#endif
